config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :gossip, except: [:destroy] 
  resources :users, except: [:destroy]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :city
  root 'gossip#index'
  get '/welcome/:first_name', to: 'dynamic#welcome' #mettre dans controller user

  resources :sessions, only:[:new, :create, :destroy]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users 	#City en relation 1-N avec User
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user		#Comment en relation N-1 avec user et gossip et en relation N-1 avec Like 
	belongs_to :gossip
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, length: { minimum: 2, maximum: 14}
	validates :content, presence: true 
    has_many :tag_lists 		#Gossip en relation N-1 avec User et en relation 1-N avec Comment et Like, et en relation N-N avec Tags
	has_many :tags, through: :tag_lists
	belongs_to :user
	has_many :comments
	has_many :likes
	belongs_to :city 

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user		#Like est en relation N-1 avec User, comment et Gossip et dont ces 2 derniers sont optionnels
	belongs_to :comment, optional: true
	belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"      #PrivateMessage est en relation 1-N avec User en utilisant une classe_name et en relation N-N avec User pour les recipient
	has_many :recipients
	has_many :users, through: :recipients
end

app/models/recipient.rb
class Recipient < ApplicationRecord
    belongs_to :private_message   #Recipient fait la liaison N-N entre privatemessage et user pour les receveurs
	belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_lists		#Tag a une relation N-N avec Gossip
	has_many :gossips, through: :tag_lists
end

app/models/tag_list.rb
class TagList < ApplicationRecord
    belongs_to :gossip	#TagList fait la relatin N-N entre Tag et Gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city		#User est en relation N-1 avec City, en relation 1-N avec Like, comment ,gossip et privatemessage et en relation N-N avec private message
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :recipients
	has_many :private_messages, through: :recipients
	has_many :comments
	has_many :likes
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else 
            @current_user = nil
        end 
    end 
end

app/controllers/city_controller.rb
class CityController < ApplicationController
    def index
        @city = City.all
        @gossip = Gossip.all
    end 

    def show 
        @city = City.find(params[:id])
        @user = User.where(city_id: @city)
    end 

    def create 
    end 

    def update
    end 

    def new 
    end 
end 

app/controllers/contact_controller.rb
class ContactController < ApplicationController 
    def index 
    end 
end 

app/controllers/dynamic_controller.rb
class DynamicController < ApplicationController
  def gossip
    @gossip = Gossip.all
    @user = User.all
  end

  def user
    @user = User.all
    @gossip = Gossip.all
  end

  def welcome
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

    def index 
        @gossip = Gossip.all
        @user = User.all
    end 

    def show 
    end 

    def new 
    end 

    def create 
        @gossip = Gossip.new(title:params["gossip_title"], content:params["gossip_content"], user_id: 31)
        
        if @gossip.save 
            puts "C'est vrai"

            redirect_to gossip_index_path
        else
                render new_gossip_path
                
        end
    end 

    def edit 
        @gossip = Gossip.find(params[:id])
    end 

    def update 
            @gossip =Gossip.find(params[:id])
            if @gossip.update(title: params[:gossip_title], content: params[:gossip_content])
              redirect_to @gossip
            else
              render :edit
            end
    end 

#    protected
#    def params_gossip
#        params.require(:gossip).permit(:title, :content)
#    end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id 
        redirect_to root_url, notice: "Logged in"
      
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"  
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @gossip= Gossip.all
    @user = User.all
  end
  
  def team
  end

  def contact
  end 
end

app/controllers/team_controller.rb
class TeamController < ApplicationController 
    def index 
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def index 
    end 

    def show
        @user = User.all 
        @gossip = Gossip.all
    end 

    def new 
        @user = User.new
    end 

    def create 
       @user = User.new(email:params[:email], password:params[:password], city: City.first)
       if @user.save
        redirect_to root_path

       else 
        puts "="*90
           @user.errors.full_messages
        puts "="*90
       end

    end 

    def edit 
    end 

    def update 
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/city/index.html.erb
<h1>Villes </h1>
  </div>
   <%  @city.each do |ville|%>
  <ul>
    <li class="list-group-item">
    <%=ville.name %> </li>
    <%= link_to "Voir la ville", city_path(ville.id)%>
  </ul>
</div>
<%end%>

app/views/city/show.html.erb
<h1> <%= City.find(params[:id]).name%> </h1>
<% @city.users.each do |ville| %>
<%= ville.gossips%><br/>
<% end %>

<div>
</div>

<% @user.each do |utilisateur|  %>
<%=utilisateur.gossip.content %>
<% end  %>

app/views/contact/index.html.erb
<h1>Contact</h1>
<p>Pour nous contacter vous pouvez envoyer un mail à l'adresse suivante : 
<br/>
benjamin.bertrandf@gmail.com
<br/>
Ou send nudes au 0631530435
</p>

app/views/dynamic/index.html.erb
<h1>Dynamic#index</h1>
<p>Find me in app/views/dynamic/index.html.erb</p>

app/views/dynamic/welcome.html.erb
<h1>Bienvenue <%= params[:first_name] %></h1>
<br/>
<p>C'est un super site de gossip, j'espère qu'il te plait ! </p>
<p><%= link_to "Voir tous les gossips", home_path %></p>

app/views/gossip/edit.html.erb
<html>
<h1> Modifier le gossip </h1>

<p> Titre : <%= Gossip.find(params[:id]).title %><br/>
    Contenu : <%= Gossip.find(params[:id]).content %><br/>
    Auteur : <%= link_to "#{User.find(Gossip.find(params[:id]).user_id).first_name} #{User.find(Gossip.find(params[:id]).user_id).last_name}", user_path(Gossip.find(params[:id]).user_id.to_i) %> <br/>
    Créer le : <%= Gossip.find(params[:id]).created_at.to_date %><br/>
 </p>

<div>
    <h1> Change ce potin!</h1>

 <%= form_tag url_for(action: 'update'), method: "patch" do %>
  <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', value = @gossip.title %>
      <br /> <br />

      <%= label_tag 'Body' %>
      <%= text_area_tag 'content', value = @gossip.content %>
      <br /> <br />

      <%= submit_tag "Valider" %>

    <% end %>

</div>
</html>

app/views/gossip/index.html.erb
<p id="notice"><%= notice %></p>

<h1>привет bienvenue dans les Gossips</h1>
<h3>Voici nos plus vilains gossips</h3>
<div class="card-deck">
    <% @gossip.each do |gossip| %> <!-- -->
    <div class="col-sm-4 mb-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"> Gossip n°<%= gossip.id %></h5>
                <p class="card-text"><%= gossip.title %></p>
                <p class="card-text"><%= @user.find(gossip.user_id).first_name %> <%= @user.find(gossip.user_id).last_name %></p>
                <p class="card-text"><%= link_to "Voir ce Gossip", gossip_path(gossip.id) %></p>
                <% if current_user %>
     <%= link_to "modifier le gossip", edit_gossip_path(gossip.id)%>
    <% else %>
    <li><%= link_to "Sign Up", new_user_path %> Si vous n'avez pas de compte </li>
    <li><%= link_to "Log In", sessions_create_path %> pour se connecter </li>
    <% end %>
                
            </div>
        </div>
    </div>
    <% end %>
 </div>

app/views/gossip/new.html.erb
<h1>Créer son gossip</h1>

 <body>
    <!-- ... -->
    

    <%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      <%= label_tag 'Titre' %>
      <%= text_field_tag 'gossip_title' %>
      <br /> <br />

      <%= label_tag 'Gossip' %>
      <%= text_area_tag 'gossip_content' %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

    <% end %>

   
    <!-- ... -->
  </body>

app/views/gossip/show.html.erb
<h1>Voici le Gossip n°<%= params[:id]%></h1>

<p> Titre : <%= Gossip.find(params[:id]).title %><br/>
    Contenu : <%= Gossip.find(params[:id]).content %><br/>
    Auteur : <%= link_to "#{User.find(Gossip.find(params[:id]).user_id).first_name} #{User.find(Gossip.find(params[:id]).user_id).last_name}", user_path(Gossip.find(params[:id]).user_id.to_i) %> <br/>
    Créer le : <%= Gossip.find(params[:id]).created_at.to_date %><br/>
 </p>

app/views/team/index.html.erb
<h1>Voici notre dream team</h1>
<p>L'équipe :</p>

<ul>
    <li>Louis</li>
    <li>Philippe</li>
    <li>Hermine</li>
    <li>Jordan</li>
    <li>Dimitri</li>
    <li>Benjamin</li>
</ul>

app/views/users/new.html.erb
<h1>S'inscrire</h1>

<%= form_tag users_path do |form| %>
    <div class="Email">
    <%= text_field_tag :email %>
    </div>

     <div class="Password">
    <%= password_field_tag :password %>
    </div>

    <div class="actions">
    <%= submit_tag "Login"%>
    </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.find(params[:id]).first_name%> <%= @user.find(params[:id]).last_name%> </h1>

<p> Utilisateur n°<%=@user.find(params[:id]).id%><br/>
    Age : <%=@user.find(params[:id]).age%><br/>
    Description : <%=@user.find(params[:id]).description%><br/>
</p>

<div>
    <h2>Ses Gossips : </h2>
    <% @gossip.where(user: params[:id]).each do |gossip| %>
    <p>
          Gossip n°<%= gossip.id %><br/>
          <%= gossip.title %><br/>
          <%= link_to "Voir ce Gossip", gossip_path(gossip.id) %>
      <%end%>
    </p>
  
</div>