config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :gossip, except: [:destroy] 
  resources :users, except: [:destroy]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :city
  root 'gossip#index'
  get '/welcome/:first_name', to: 'dynamic#welcome' #mettre dans controller user

  resources :sessions, only:[:new, :create, :destroy]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users 	#City en relation 1-N avec User
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user		#Comment en relation N-1 avec user et gossip et en relation N-1 avec Like 
	belongs_to :gossip
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, length: { minimum: 2, maximum: 14}
	validates :content, presence: true 
    has_many :tag_lists 		#Gossip en relation N-1 avec User et en relation 1-N avec Comment et Like, et en relation N-N avec Tags
	has_many :tags, through: :tag_lists
	belongs_to :user
	has_many :comments
	has_many :likes
	belongs_to :city 

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user		#Like est en relation N-1 avec User, comment et Gossip et dont ces 2 derniers sont optionnels
	belongs_to :comment, optional: true
	belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"      #PrivateMessage est en relation 1-N avec User en utilisant une classe_name et en relation N-N avec User pour les recipient
	has_many :recipients
	has_many :users, through: :recipients
end

app/models/recipient.rb
class Recipient < ApplicationRecord
    belongs_to :private_message   #Recipient fait la liaison N-N entre privatemessage et user pour les receveurs
	belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_lists		#Tag a une relation N-N avec Gossip
	has_many :gossips, through: :tag_lists
end

app/models/tag_list.rb
class TagList < ApplicationRecord
    belongs_to :gossip	#TagList fait la relatin N-N entre Tag et Gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city		#User est en relation N-1 avec City, en relation 1-N avec Like, comment ,gossip et privatemessage et en relation N-N avec private message
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :recipients
	has_many :private_messages, through: :recipients
	has_many :comments
	has_many :likes
	has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
    def index
        @city = City.all
        @gossip = Gossip.all
    end 

    def show 
        @city = City.find(params[:id])
        @user = User.where(city_id: @city)
    end 

    def create 
    end 

    def update
    end 

    def new 
    end 
end 

app/controllers/contact_controller.rb
class ContactController < ApplicationController 
    def index 
    end 
end 

app/controllers/dynamic_controller.rb
class DynamicController < ApplicationController
  def gossip
    @gossip = Gossip.all
    @user = User.all
  end

  def user
    @user = User.all
    @gossip = Gossip.all
  end

  def welcome
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

    def index 
        @gossip = Gossip.all
        @user = User.all
    end 

    def show 
    end 

    def new 
    end 

    def create 
        @gossip = Gossip.new(title:params["gossip_title"], content:params["gossip_content"], user_id: 31)
        
        if @gossip.save 
            puts "C'est vrai"

            redirect_to gossip_index_path
        else
                render new_gossip_path
                
        end
    end 

    def edit 
        @gossip = Gossip.find(params[:id])
    end 

    def update 
            @gossip =Gossip.find(params[:id])
            if @gossip.update(title: params[:gossip_title], content: params[:gossip_content])
              redirect_to @gossip
            else
              render :edit
            end
    end 

#    protected
#    def params_gossip
#        params.require(:gossip).permit(:title, :content)
#    end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id 
        redirect_to root_url, notice: "Logged in"
      
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"  
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @gossip= Gossip.all
    @user = User.all
  end
  
  def team
  end

  def contact
  end 
end

app/controllers/team_controller.rb
class TeamController < ApplicationController 
    def index 
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def index 
    end 

    def show
        @user = User.all 
        @gossip = Gossip.all
    end 

    def new 
        @user = User.new
    end 

    def create 
       @user = User.new(email:params[:email], password:params[:password], city: City.first)
       if @user.save
        redirect_to root_path

       else 
        puts "="*90
           @user.errors.full_messages
        puts "="*90
       end

    end 

    def edit 
    end 

    def update 
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">The Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <li class="nav-item nav-link active"> <%= link_to "Home", gossip_index_path %> <span class="sr-only">(current)</span></li>
            <li class="nav-item nav-link"> <%= link_to "Team", team_index_path %></li>
            <li class="nav-item nav-link"> <%= link_to "Contact", contact_index_path %></li>
            <li><% if current_user %>
   Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", sessions_destroy_path %>
<% else %>
  <li class="nav-item nav-link mr-sm-8"><%= link_to "Sign Up", new_user_path %></li>
  <li class="nav-item nav-link mr-sm-8"><%= link_to "Log In", sessions_create_path %></li>
<% end %></li>
            
           
          </div>
        </div>
     </nav>
  </header>
  <div class="main">
    <%= yield %>
       <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </div>  
  </body>
</html>